spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: thisisstrongerpassword
log4j:
  category:
    org:
      springframework:
        data:
          neo4j: DEBUG


logging:
  level:
    org:
      neo4j:
        ogm:
          drivers:
            bolt:
              request:
                BoltRequest: DEBUG


