spring:
  datasource:
    url: jdbc:mariadb://localhost:4906/dadange
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-dadange
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
